# first_level_name = "test_room"
first_level_name = "another_test_room"

[main_actor]
model    = "assets/models/mona_sax/export/glb/mona.glb"
collider = "assets/models/mona_sax/export/glb/collider.glb"

[[levels]]
name          = "test_room"
room_glb      = "assets/models/test_rooms/export/test_floor/glb/test_rooms.glb"
walk_area_glb = "assets/models/test_rooms/export/test_floor/glb/walk_area.glb"

	#TODO use camera from blender
	[levels.camera]
	pos    = [1.0, 2.0, 4.0]
	target = [0.0, 1.0, 0.0]

	[[levels.interactables]]
	name = "interactable_h_half"
	glb  = "assets/models/test_rooms/export/test_floor/glb/interactable_h_half.glb"

	[[levels.interactables]]
	name = "interactable_h_2"
	glb  = "assets/models/test_rooms/export/test_floor/glb/interactable_h_2.glb"

[[levels]]
name          = "another_test_room"
room_glb      = "assets/models/another_test_room/export/glb/room.glb"
walk_area_glb = "assets/models/another_test_room/export/glb/walk_area.glb"

	[levels.camera]
	pos    = [5.0, 3.0, 10.0]
	target = [0.0, 0.0, 0.0]

	[[levels.interactables]]
	name = "rusty_lever"
	#TODO mock here
	glb = "assets/models/another_test_room/export/glb/walk_area.glb"
