first_level_name = "test_room"
# first_level_name = "another_test_room"

[[actors]]
name     = "mona"
model    = "assets/models/mona_sax/export/glb/mona.glb"
collider = "assets/models/mona_sax/export/glb/collider.glb"

[[actors]]
name  = "cleaner_a"
model = "assets/models/cleaner_a/export/cleaner_a.glb"


[[levels]]
name     = "test_room"
room_glb = "assets/models/test_rooms/export/test_floor/glb/test_rooms.glb"

	[[levels.dialogues]]
	id = "cleaner_dialog"	# must have the same name as interactable
	lines = [
		{ speaker = "mona", text = "Hey, how's it going?" },
		{ speaker = "cleaner_a", text = "Busy day. Floor's not gonna mop itself." },
		{ speaker = "mona", text = "Fair enough." },
		{ speaker = "cleaner_a", text = "..." },
	]

[[levels]]
name     = "another_test_room"
room_glb = "assets/models/another_test_room/export/glb/room.glb"
